%% Setup Drone
m = 320;  % Updated mass of the drone in kg
I = [[0.1,0,0];[0,0.1,0];[0,0,0.08]]

% sample time
ts = 0.01

% Initial States (Initial XYZ is generated by XYZsignal script)
Euler_0 = [0;0;0]
XYZ_0 = [0;0;0]
body_rate_0 = [0;0;0]

% Environment
g = [0;0;-9.8]
